// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace cn.jpush.api.push.notification
{
	public class Notification
	{
		private string alert;
		private HashSet<PlatformNotification> notifications;

		private Notification (string alert,HashSet<PlatformNotification> notifications)
		{
			this.alert = alert;
			this.notifications = notifications;
		}
		public static Notification alertNotification(string alert){
			return new Notification (alert,null);
		}


	}
}

