using cn.jpush.api.push.notificaiton;
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace cn.jpush.api.push.mode
{
    public class Notification : IPushMode
	{
        private  String alert;
        private  HashSet<PlatformNotification> notifications;
    
        private Notification(String alert, HashSet<PlatformNotification> notifications)
        {
            this.alert = alert;
            this.notifications = notifications;
        }
        public static Notification alertNotificaiton(string alert)
        {
            return new Notification(alert, null);
        }

        public object toJsonObject()
        {
            Dictionary<string, object> dict = new Dictionary<string, object>();
            if (alert != null)
            {
                dict.Add(PlatformNotification.ALERT, alert);
            }
            foreach (var item in this.notifications)
            {
                dict.Add(item.getPlatformName(), item.toJsonObject());
            }
            return dict;
        }
	}
}

